Repository Ospac/Rolling, pull requests merged in 2025-07, with the labels that each got.

#6 feat: 메인화면 UI
  main.html
Labels: ✨ Feature

#9 [공통] 디자인 토큰 및 글로벌 SCSS
  global.d.ts
  jsconfig.json
  package-lock.json
  package.json
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard-Thin.woff2
  src/styles/_font.scss
  src/styles/_reset.scss
  src/styles/_token.scss
  src/styles/common.scss
  vite.config.js
Labels: ✨ Feature

#15 [PostDetail] 페이지 구조 세팅 및 카드 리스트 UI 작업
  src/components/post/AddMessageButton.jsx
  src/components/post/AddMessageButton.module.scss
  src/components/post/PostCard.jsx
  src/components/post/PostCard.module.scss
  src/components/post/PostCardList.jsx
  src/components/post/PostCardList.module.scss
  src/main.jsx
  src/pages/PostDetail/mock.js
Labels: ✨ Feature, 🎨 UI

#19 [PostDetail] 롤링페이퍼 메시지 작성 링크 연결 및 카드 UI스타일 개선
  src/components/post/AddMessageButton.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostCardList.jsx
  src/components/post/PostCardList.module.scss
  src/main.jsx
  src/pages/PostDetail/AddMessageButton.jsx
  src/pages/PostDetail/AddMessageButton.module.scss
  src/pages/PostDetail/PostCard.jsx
  src/pages/PostDetail/PostCard.module.scss
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/PostCardList.module.scss
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/mock.js
Labels: ✨ Feature, 🎨 UI

#21 [공통]디자인 토큰 및 함수 추가
  src/components/layout/Header.module.scss
  src/styles/_token.scss
  src/styles/_util.scss
Labels: ✨ Feature, ♻️ Refactor

#24 [공통] api 세팅
  src/apis/constants.js
  src/apis/customFetch.js
  src/apis/messages.js
  src/apis/reactions.js
  src/apis/recipients.js
  src/hooks/useAsync.js
  src/layouts/Layout.module.scss
  src/styles/_font.scss
  src/styles/_reset.scss
  src/styles/_token.scss
Labels: ✨ Feature

#34 [3차배포]
  src/api/message.js
  src/components/layout/Header.jsx
  src/components/layout/Header.module.scss
  src/components/ui/Button.jsx
  src/components/ui/Button.module.scss
  src/components/ui/EmojiBadge.jsx
  src/components/ui/ProfileIcon.jsx
  src/components/ui/Toast.module.scss
  src/components/ui/constants.js
  src/layouts/Layout.module.scss
  src/main.jsx
  src/pages/PostDetail/AddMessageButton.module.scss
  src/pages/PostDetail/PostCard.module.scss
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/PostCardList.module.scss
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/mock.js
  src/styles/common.scss
  src/styles/reset.scss
  src/vite-env.d.ts
Labels: 🌏 Deploy

#45 Feature/dark mode
  src/assets/fonts/Poppins/Poppins-Bold.woff
  src/assets/fonts/Pretendard/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard/Pretendard-Light.woff2
  src/assets/fonts/Pretendard/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard/Pretendard-Thin.woff2
  src/assets/icons/dark_mode.svg
  src/assets/icons/light_mode.svg
  src/assets/icons/logo.svg
  src/components/PostNav/AuthorCount.module.scss
  src/components/PostNav/index.module.scss
  src/components/layout/DarkModeToggle.jsx
  src/components/layout/DarkModeToggle.module.scss
  src/components/layout/Header.jsx
  src/components/layout/Header.module.scss
  src/layouts/ThemeLayout.jsx
  src/main.jsx
  src/pages/PostDetail/PostCard.module.scss
  src/styles/_font.scss
  src/styles/_token.scss
  src/styles/reset.scss
  src/styles/theme.scss
Labels: ✨ Feature

#42 [PostNav] 리다이렉션 수정 / 리액션 수정 / useRecipientId.js 생성
  index.html
  public/icons/favicon.svg
  public/images/previewImg.png
  src/api/message.js
  src/components/PostNav/AuthorCount.jsx
  src/components/PostNav/AuthorImage.jsx
  src/components/PostNav/AuthorImage.module.scss
  src/components/PostNav/EmojiAddButton.jsx
  src/components/PostNav/EmojiBar.jsx
  src/components/PostNav/ShareKakaoButton.jsx
  src/components/PostNav/ShareUrlButton.jsx
  src/components/PostNav/index.jsx
  src/components/PostNav/mock.json
  src/hooks/useRecipientId.js
  src/layouts/PostPageLayout.jsx
Labels: 🔨Fix, ♻️ Refactor

#57 [PostDetail] 메시지 / 사용자 정보 API 연동 및 배경색 처리
  package-lock.json
  package.json
  src/assets/images/plus.png
  src/pages/PostDetail/AddMessageButton.jsx
  src/pages/PostDetail/AddMessageButton.module.scss
  src/pages/PostDetail/CardDetail.jsx
  src/pages/PostDetail/CardDetail.module.scss
  src/pages/PostDetail/CardDetailShared.module.scss
  src/pages/PostDetail/Modal.jsx
  src/pages/PostDetail/Modal.module.scss
  src/pages/PostDetail/PostCard.jsx
  src/pages/PostDetail/PostCard.module.scss
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/mock.js
Labels: ✨ Feature

#56 [PostCreate] UI + 기능 구현
  src/api/message.js
  src/apis/constants.js
  src/apis/images.js
  src/apis/recipients.js
  src/assets/icons/enabled.svg
  src/components/ui/InputField.module.scss
  src/components/ui/RelationBadge.jsx
  src/main.jsx
  src/pages/PostCreate/BackgroundSelect.jsx
  src/pages/PostCreate/BackgroundSelect.module.scss
  src/pages/PostCreate/Box.module.scss
  src/pages/PostCreate/ColorBox.jsx
  src/pages/PostCreate/ImageBox.jsx
  src/pages/PostCreate/PostCreateForm.jsx
  src/pages/PostCreate/PostCreateForm.module.scss
  src/pages/PostCreate/constants.js
  src/pages/PostCreate/index.jsx
  src/pages/PostCreate/index.module.scss
  src/styles/theme.scss
Labels: ✨ Feature

#58 [Message] 텍스트 에디터 및 버튼 활성화 로직 추가
  package-lock.json
  package.json
  src/pages/List/index.jsx
  src/pages/Message/ContentEditor.jsx
  src/pages/Message/ContentEditor.module.scss
  src/pages/Message/MessageForm.jsx
  src/pages/Message/MessageForm.module.scss
  src/pages/message/ContentEditor.jsx
  src/pages/message/ContentEditor.module.scss
  src/pages/message/MessageForm.jsx
  src/pages/message/MessageForm.module.scss
Labels: ✨ Feature

#62 [PostDetail] 메시지 폰트 동적 적용 기능 구현 및 웹 폰트 세팅 추가
  package-lock.json
  src/assets/fonts/NanumMyeongjo/NanumMyeongjo-Regular.woff2
  src/assets/fonts/NanumSonPyeonJiCe/NanumSonPyeonJiCe-Regular.woff2
  src/assets/fonts/NotoSans/NotoSansKR-Regular.woff2
  src/pages/PostDetail/CardDetail.jsx
  src/pages/PostDetail/CardDetailShared.module.scss
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/mock.js
  src/styles/_font.scss
Labels: ✨ Feature

#67 [List+Message] List 및 Message 페이지 API 연동/반응형 구현
  package-lock.json
  package.json
  src/apis/uploads.js
  src/assets/images/profile1.png
  src/assets/images/profile2.png
  src/pages/List/CardItem.jsx
  src/pages/List/CardItem.module.scss
  src/pages/List/CardSlider.jsx
  src/pages/List/CardSlider.module.scss
  src/pages/List/CardSliderSection.jsx
  src/pages/List/CardSliderSection.module.scss
  src/pages/List/ListPage.module.scss
  src/pages/List/SectionTitle.jsx
  src/pages/List/SectionTitle.module.scss
  src/pages/List/SlideButton.module.scss
  src/pages/List/index.jsx
  src/pages/Message/ContentEditor.module.scss
  src/pages/Message/FontSelector.module.scss
  src/pages/Message/MessageForm.jsx
  src/pages/Message/MessageForm.module.scss
  src/pages/Message/ProfileUploader.jsx
  src/pages/Message/ProfileUploader.module.scss
  src/pages/Message/RelationshipSelect.module.scss
  src/pages/message/ContentEditor.module.scss
  src/pages/message/FontSelector.module.scss
  src/pages/message/MessageForm.jsx
  src/pages/message/MessageForm.module.scss
  src/pages/message/ProfileUploader.jsx
  src/pages/message/ProfileUploader.module.scss
  src/pages/message/RelationshipSelect.module.scss
Labels: ✨ Feature, ♻️ Refactor

#66 [PostEdit] UI 및 api연결
  index.html
  package-lock.json
  package.json
  public/images/previewImg.png
  src/apis/customFetch.js
  src/apis/messages.js
  src/assets/icons/delete.svg
  src/components/PostNav/AuthorImage.jsx
  src/components/PostNav/AuthorImage.module.scss
  src/components/PostNav/EmojiAddButton.jsx
  src/components/PostNav/EmojiAddButton.module.scss
  src/components/PostNav/EmojiBar.jsx
  src/components/PostNav/EmojiBar.module.scss
  src/components/PostNav/EmojiList.jsx
  src/components/PostNav/ShareButton.jsx
  src/components/PostNav/ShareKakaoButton.jsx
  src/components/PostNav/Toast.jsx
  src/components/PostNav/Toast.module.scss
  src/components/PostNav/index.jsx
  src/components/PostNav/mock.json
  src/components/PostNav/useEmojiClick.js
  src/components/ui/EmojiBadge.module.scss
  src/hooks/useRecipientId.js
  src/layouts/MainLayout.jsx
  src/layouts/PostPageLayout.jsx
  src/pages/PostDetail/AddMessageButton.jsx
  src/pages/PostDetail/Modal.jsx
  src/pages/PostDetail/PostCard.jsx
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/PostCardList.module.scss
  src/pages/PostDetail/index.jsx
  src/pages/PostEdit/DeleteButton.module.scss
  src/pages/PostEdit/DeleteModal.jsx
  src/pages/PostEdit/DeleteModal.module.scss
  src/pages/PostEdit/EditButton.jsx
  src/pages/PostEdit/MessageEdit.jsx
  src/pages/PostEdit/MessageEdit.module.scss
Labels: ✨ Feature, ♻️ Refactor

#65 [NotFound] 페이지 완료
  src/assets/icons/codeit404.svg
  src/main.jsx
  src/pages/NotFound.jsx
  src/pages/NotFound/NotFound.module.scss
  src/pages/NotFound/index.jsx
Labels: ✨ Feature

#64 [PostCreate] form 유효성 검사 코드 정리 및 로딩 화면 추가
  src/apis/recipients.js
  src/components/ui/LoadingDots.jsx
  src/components/ui/LoadingDots.module.scss
  src/hooks/useImageLoader.js
  src/pages/PostCreate/BackgroundSelect.jsx
  src/pages/PostCreate/Box.module.scss
  src/pages/PostCreate/ColorBox.jsx
  src/pages/PostCreate/ColorBoxes.jsx
  src/pages/PostCreate/ImageBox.jsx
  src/pages/PostCreate/ImageBoxes.jsx
  src/pages/PostCreate/PostCreateForm.jsx
  src/styles/_util.scss
Labels: ✨ Feature, ♻️ Refactor

#69 [PostDetail] 사용자 배경 스타일 동적 적용 및 카드/모달 반응형 UI 구현
  src/pages/PostDetail/CardDetail.module.scss
  src/pages/PostDetail/Modal.module.scss
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostDetail/PostCardList.module.scss
  src/pages/PostDetail/index.jsx
Labels: ✨ Feature

#71 [postEdit] 메시지 수정
  package-lock.json
  src/apis/messages.js
  src/components/PostNav/index.jsx
  src/pages/List/CardItem.jsx
  src/pages/List/CardItem.module.scss
  src/pages/List/CardSliderSection.jsx
  src/pages/List/index.jsx
  src/pages/Message/FontSelector.jsx
  src/pages/Message/MessageForm.jsx
  src/pages/Message/ProfileUploader.jsx
  src/pages/PostDetail/PostCard.jsx
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostEdit/MessageEdit.jsx
  src/pages/message/ContentEditor.jsx
  src/pages/message/FontSelector.jsx
  src/pages/message/MessageForm.jsx
  src/pages/message/ProfileUploader.jsx
Labels: ✨ Feature

#74 [PostDeatil] cardBox hover 효과 개선(shadow, transform)
  src/pages/PostDetail/CardDetail.module.scss
  src/pages/PostDetail/CardDetailShared.module.scss
Labels: 🎨 UI

#79 [PostEdit] 오류 수정 및 누락추가
  public/images/previewImg.png
  src/layouts/PostPageLayout.jsx
  src/pages/PostDetail/AddMessageButton.jsx
  src/pages/PostDetail/PostCardList.jsx
  src/pages/PostEdit/DeleteModal.jsx
  src/pages/PostEdit/MessageEdit.jsx
Labels: 🔨Fix
